import type { Card, CardType } from "../../cards/schema";
import { stripGlossaryMarks } from "../glossary";
import { DEFAULT_SITE_URL } from "../site";
import type { LoadedContent } from "./load";
import type { Lesson } from "./schema";

/**
 * The content export (`npm run export:content` → `docs/content-export.md`): a plain summary of every
 * course for planning videos and posts. Pure, so it's tested without the file system.
 *
 * It only reads what learners see before answering: explainer text and card prompts. It never
 * includes quiz cards, correct answers, explanations, hints or nudges.
 */

/** Hands-on types first: these make the best clips. Static cards are never "interactive picks". */
const TYPE_RANK: Partial<Record<CardType, number>> = {
  simulator: 0,
  teardown: 1,
  packet_path: 2,
  terminal: 3,
  scenario: 4,
  hotspot: 5,
  sort_bins: 6,
  binary_toggle: 7,
  match_pairs: 8,
  drag_to_order: 9,
  numeric_input: 10,
  multiple_choice: 11,
};

const TYPE_LABEL: Record<CardType, string> = {
  explainer: "Explainer",
  photo: "Photo",
  multiple_choice: "Multiple choice",
  drag_to_order: "Put in order",
  binary_toggle: "Binary switches",
  numeric_input: "Number answer",
  match_pairs: "Match pairs",
  packet_path: "Route a packet",
  terminal: "Terminal",
  hotspot: "Tap the picture",
  teardown: "Take it apart",
  simulator: "Simulator",
  scenario: "Choose what happens",
  sort_bins: "Sort into groups",
};

const PICKS_PER_LESSON = 3;
const KEY_FACTS_PER_EXPLAINER = 2;
const SURPRISES_PER_LESSON = 3;
const MAX_PROMPT = 220;

/** Words that usually mark a fact worth repeating in a video. Numbers count too. */
const SURPRISING = /\b(billion|billions|million|millions|thousand|thousands|trillion|every second|actually|in fact|even though)\b|\d{2,}/i;

/** Markdown to one line of readable text: glossary marks and link syntax gone, bold kept. */
export function plainText(markdown: string): string {
  return stripGlossaryMarks(markdown)
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\s*(?:[-*]|\d+\.)\s+/gm, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Sentences of an explainer body (lists become their own sentences). */
export function sentences(markdown: string): string[] {
  return stripGlossaryMarks(markdown)
    .split(/\n+/)
    .flatMap((line) => plainText(line).split(/(?<=[.!?])\s+(?=[A-Z"'`*(])/))
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

export function truncate(text: string, max = MAX_PROMPT): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  return `${cut.slice(0, Math.max(cut.lastIndexOf(" "), max / 2)).replace(/[\s,;:.]+$/, "")}…`;
}

/** The sentences that name an idea in bold: the lesson's key facts, up to two per explainer. */
export function keyFacts(lesson: Lesson): { title: string; facts: string[] }[] {
  return lesson.cards.flatMap((card) => {
    if (card.type !== "explainer") return [];
    const facts = sentences(card.body)
      .filter((s) => s.includes("**"))
      .slice(0, KEY_FACTS_PER_EXPLAINER);
    return facts.length ? [{ title: card.title, facts }] : [];
  });
}

/** Explainer sentences with big numbers or "actually"-style surprises, not already key facts. */
export function surprisingFacts(lesson: Lesson): string[] {
  const used = new Set(keyFacts(lesson).flatMap((k) => k.facts));
  return lesson.cards
    .flatMap((card) => (card.type === "explainer" ? sentences(card.body) : []))
    .filter((s) => !used.has(s) && !/^Next\b/.test(s) && (s.match(/[A-Za-z]{2,}/g) ?? []).length >= 7 && SURPRISING.test(s))
    .slice(0, SURPRISES_PER_LESSON);
}

type Promptable = Extract<Card, { prompt: string }>;

/** The most hands-on cards in a lesson, in lesson order, shown by their prompt only. */
export function interactivePicks(lesson: Lesson): { type: string; prompt: string }[] {
  const candidates = lesson.cards
    .map((card, index) => ({ card, index }))
    .filter((c): c is { card: Promptable; index: number } => "prompt" in c.card && TYPE_RANK[c.card.type] !== undefined);
  return candidates
    .sort((a, b) => TYPE_RANK[a.card.type]! - TYPE_RANK[b.card.type]! || a.index - b.index)
    .slice(0, PICKS_PER_LESSON)
    .sort((a, b) => a.index - b.index)
    .map(({ card }) => ({
      type: card.type === "hotspot" && card.mode === "explore" ? "Explore the picture" : TYPE_LABEL[card.type],
      prompt: truncate(plainText(card.prompt)),
    }));
}

export function taggedLink(lessonId: string): string {
  return `${new URL(DEFAULT_SITE_URL).host}/from/<platform>/${lessonId}`;
}

export function renderContentExport(content: LoadedContent): string {
  const out: string[] = [
    "# Content export",
    "",
    "Generated by `npm run export:content` from `/content`. Don't edit by hand; run the script again after content changes.",
    "",
    "For planning videos and posts. It only uses what learners see before answering (explainers and card prompts):",
    "**no quiz questions or answers**, and no explanations, hints or nudges.",
    "",
    "**Tagged links:** replace `<platform>` with one lower-case word per platform or video (`tiktok`, `youtube`, `tiktok-ram`),",
    "so Vercel Analytics shows where visitors came from. Pro lessons ask visitors to upgrade, so link to free lessons where you can.",
    "",
  ];

  for (const course of content.courses) {
    out.push(`## ${course.title}`, "", course.description, "");
    for (const mod of course.modules) {
      out.push(`### Module ${mod.order}: ${mod.title} (${mod.access === "pro" ? "Pro" : "Free"})`, "", mod.description, "");
      for (const outline of mod.lessons) {
        const lesson = content.lessons.get(outline.id);
        if (!lesson) continue;
        if (lesson.kind === "quiz") {
          const questions = lesson.cards.length;
          out.push(`#### Module quiz (${questions} question${questions === 1 ? "" : "s"})`, "", "Not exported, so the answers stay secret.", "");
          continue;
        }
        out.push(`#### ${lesson.title}`, "", `- **Access:** ${lesson.access === "pro" ? "Pro" : "Free"}`, `- **Link:** \`${taggedLink(lesson.id)}\``, "");

        const facts = keyFacts(lesson);
        if (facts.length) {
          out.push("**Key facts**", "");
          for (const { title, facts: lines } of facts) out.push(`- *${title}:* ${lines.join(" ")}`);
          out.push("");
        }
        const picks = interactivePicks(lesson);
        if (picks.length) {
          out.push("**Best interactive cards**", "");
          for (const pick of picks) out.push(`- ${pick.type}: ${pick.prompt}`);
          out.push("");
        }
        const surprises = surprisingFacts(lesson);
        if (surprises.length) {
          out.push("**Surprising facts**", "");
          for (const s of surprises) out.push(`- ${s}`);
          out.push("");
        }
      }
    }
  }
  return `${out.join("\n").trimEnd()}\n`;
}
