"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { deleteAccountAction } from "@/app/actions/account";
import { Button } from "@/components/ui/Button";
import { DailyGoalSetting } from "./DailyGoalSetting";
import { ManageProPanel } from "@/components/pro/ManageProPanel";
import { LeagueAccountSettings } from "@/components/leagues/LeagueAccountSettings";
import { CertificatesPanel } from "@/components/certificates/CertificatesPanel";
import { DeleteIcon, SignOutIcon } from "@/components/ui/icons";
import { trackEvent } from "@/lib/analytics";
import { takeSignupLesson } from "@/lib/auth/afterSignIn";
import { useAuth } from "@/lib/auth/AuthProvider";
import { usePro } from "@/lib/pro/ProProvider";
import { Avatar } from "@/components/rewards/Avatar";
import { UsernameForm } from "./UsernameForm";
import { AvatarPanel } from "@/components/rewards/RewardsView";

const panel = "rounded-card border border-line bg-surface p-5 shadow-card";

export function AccountPanel({
  courseTitles,
  email,
  username,
  usernameGenerated = false,
  nextChange,
  welcome,
  next = "/",
}: {
  /** Course id → title, for the certificates list. */
  courseTitles: Record<string, string>;
  email: string | null;
  username: string | null;
  /** The username was generated by the app (not picked yet): picking one is free. */
  usernameGenerated?: boolean;
  /** When the next username change is allowed ("20 October"), or null for now. */
  nextChange: string | null;
  welcome: boolean;
  /** Where a new account carries on after choosing a name (e.g. the lesson that asked them to sign up). */
  next?: string;
}) {
  const router = useRouter();
  const { auth, refreshProfile, signOut } = useAuth();
  const { hasPro } = usePro();
  const [saved, setSaved] = useState(usernameGenerated ? null : username);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [pending, startTransition] = useTransition();

  async function onSaved(name: string) {
    const first = saved === null;
    setSaved(name);
    await refreshProfile();
    if (welcome && first) {
      trackEvent("signed_up", takeSignupLesson()); // a new account has just finished setting up
      router.push(next);
    }
  }

  function deleteAccount() {
    startTransition(async () => {
      await deleteAccountAction(); // redirects home when done
    });
  }

  return (
    <div className="mx-auto max-w-lesson space-y-5">
      <div className="flex items-center gap-4">
        <Avatar outfit={auth.status === "signed-in" ? auth.outfit : null} pro={hasPro} size={56} />
        <div className="min-w-0">
          <h1 className="truncate text-headline font-semibold">{saved ?? "Your account"}</h1>
          {email && <p className="text-small text-ink-muted [overflow-wrap:anywhere]">{email}</p>}
        </div>
      </div>

      {welcome && !saved && (
        <p role="status" className="rounded-card border border-accent-ink bg-accent-soft p-4 text-small">
          You&apos;re in! Pick a username. It&apos;s how other learners see you, so keep it fun and never your real name.
        </p>
      )}

      <UsernameForm className={panel} initial={username} generated={usernameGenerated} nextChange={nextChange} welcome={welcome} onSaved={(name) => void onSaved(name)} />

      <AvatarPanel className={panel} />

      <ManageProPanel className={panel} />

      <LeagueAccountSettings className={panel} />

      <CertificatesPanel className={panel} courseTitles={courseTitles} />

      <DailyGoalSetting className={panel} />

      <div className={panel}>
        <Button
          variant="secondary"
          className="w-full sm:w-auto"
          onClick={() =>
            startTransition(async () => {
              await signOut();
              router.push("/");
              router.refresh();
            })
          }
          disabled={pending}
        >
          <SignOutIcon className="size-5" /> Sign out
        </Button>
      </div>

      <div className={`${panel} border-danger`}>
        <h2 className="font-semibold">Delete account</h2>
        <p className="mt-1 text-small text-ink-muted">
          Deletes your account, your progress and your XP, and cancels any Pro subscription straight away. This can&apos;t be undone.
        </p>
        {confirmDelete ? (
          <div className="mt-4 flex flex-col gap-2 sm:flex-row">
            <Button variant="danger" onClick={deleteAccount} disabled={pending}>
              <DeleteIcon className="size-5" /> {pending ? "Deleting…" : "Yes, delete everything"}
            </Button>
            <Button variant="ghost" onClick={() => setConfirmDelete(false)} disabled={pending}>
              Keep my account
            </Button>
          </div>
        ) : (
          <Button variant="ghost" className="mt-3 text-danger" onClick={() => setConfirmDelete(true)}>
            <DeleteIcon className="size-5" /> Delete my account
          </Button>
        )}
      </div>
    </div>
  );
}
