/**
 * `npx tsx scripts/play-audit.ts [course-id]`: every lesson's play mix (RECOGNISE / PREDICT / BUILD /
 * CONSEQUENCE, core graded cards), whether it meets the target, and per-course totals. Writes
 * docs/plans/play-audit.md (all courses) and prints a summary.
 */
import fs from "node:fs";
import path from "node:path";
import { loadContent } from "../src/lib/content/load";
import { playMix, playProblems } from "../src/lib/content/play";

const only = process.argv[2];
const { courses, lessons } = loadContent();
const pct = (n: number, d: number) => (d ? `${Math.round((100 * n) / d)}%` : "–");
const lines: string[] = ["# Play audit", "", "Generated by `npx tsx scripts/play-audit.ts`. Core graded cards only; target: at least one PREDICT, at least one BUILD or CONSEQUENCE, RECOGNISE no more than half.", ""];
for (const course of courses) {
  if (only && course.id !== only) continue;
  const mine = [...lessons.values()].filter((l) => l.courseId === course.id && l.kind === "lesson");
  const total = mine.reduce((t, l) => {
    const m = playMix(l.cards);
    return { g: t.g + m.graded, r: t.r + m.recognise, p: t.p + m.predict, b: t.b + m.build, c: t.c + m.consequence, ok: t.ok + (playProblems(m).length ? 0 : 1) };
  }, { g: 0, r: 0, p: 0, b: 0, c: 0, ok: 0 });
  lines.push(`## ${course.title}`, "", `Recognise ${pct(total.r, total.g)} · Predict ${pct(total.p, total.g)} · Build ${pct(total.b, total.g)} · Consequence ${pct(total.c, total.g)} · ${total.ok} of ${mine.length} lessons meet the target`, "");
  lines.push("| Lesson | Recognise | Predict | Build | Consequence | Problems |", "|---|---|---|---|---|---|");
  for (const l of mine) {
    const m = playMix(l.cards);
    lines.push(`| ${l.title} | ${m.recognise} | ${m.predict} | ${m.build} | ${m.consequence} | ${playProblems(m).join("; ") || "meets target"} |`);
  }
  lines.push("");
  console.log(`${course.title}: ${total.ok}/${mine.length} meet the target (R ${pct(total.r, total.g)}, P ${pct(total.p, total.g)}, B ${pct(total.b, total.g)}, C ${pct(total.c, total.g)})`);
}
if (!only) fs.writeFileSync(path.join(import.meta.dirname, "..", "docs", "plans", "play-audit.md"), lines.join("\n"));
