/**
 * One sample of every card type (plus variants), for the dev-only /dev/cards playground.
 * Not course content: nothing here appears on the home page. Uses only documentation-safe
 * addresses (192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, private ranges) and example.com.
 */
import { type Card, CardSchema } from "@/cards/schema";

const raw: unknown[] = [
  {
    id: "sample-explainer",
    type: "explainer",
    difficulty: "core",
    title: "Explainer card",
    body: "Explainers teach one idea with **markdown**, `inline code` and an optional illustration. Tap a dotted term, like [[router]], for its glossary definition.",
    image: {
      src: "/illustrations/ipv4-octets.svg",
      alt: "The address 192.168.1.10 split into four boxes, each labelled 8 bits.",
      width: 640,
      height: 200,
    },
  },
  {
    id: "sample-multiple-choice",
    type: "multiple_choice",
    difficulty: "core",
    prompt: "Which of these is a **private** [[IPv4]] address?",
    options: [
      { id: "private", text: "192.168.0.20" },
      { id: "doc-a", text: "203.0.113.20", nudge: "`203.0.113.x` is one of the ranges this course uses for **public** addresses." },
      { id: "doc-b", text: "198.51.100.20", nudge: "`198.51.100.x` stands in for a **public** address here, not a private one." },
    ],
    correctOptionId: "private",
    hint: "Private addresses start with `10.`, `172.16.` to `172.31.`, or `192.168.`.",
    explanation: "Addresses starting `192.168.` are in a private range reserved for home and office networks.",
  },
  {
    id: "sample-drag-to-order",
    type: "drag_to_order",
    difficulty: "core",
    prompt: "Put the steps of loading a web page in order.",
    items: [
      { id: "dns", label: "Look up the name with DNS" },
      { id: "connect", label: "Connect to the server" },
      { id: "request", label: "Send the request" },
      { id: "render", label: "Show the page" },
    ],
    explanation: "The browser needs the server's address (DNS) before it can connect and ask for the page.",
  },
  {
    id: "sample-binary-toggle",
    type: "binary_toggle",
    difficulty: "core",
    prompt: "Make **170**.",
    target: 170,
    explanation: "170 = 128 + 32 + 8 + 2, which is `10101010`.",
  },
  {
    id: "sample-numeric-binary",
    type: "numeric_input",
    difficulty: "core",
    prompt: "Write **13** in binary.",
    hint: "13 = 8 + 4 + 1.",
    base: "binary",
    answer: 13,
    explanation: "8 + 4 + 1 = 13, so the 8, 4 and 1 bits are on: `1101`.",
  },
  {
    id: "sample-numeric-hex",
    type: "numeric_input",
    difficulty: "challenge",
    prompt: "What is **255** in hexadecimal?",
    base: "hex",
    answer: 255,
    explanation: "255 = 15 × 16 + 15, and 15 is F in hex, so 255 is `FF`.",
  },
  {
    id: "sample-numeric-decimal",
    type: "numeric_input",
    difficulty: "core",
    prompt: "How many different values can one byte hold?",
    base: "decimal",
    answer: 256,
    unit: "values",
    hint: "Each extra bit doubles the number of patterns. Start from 2 for one bit.",
    nudge: "Count the patterns, not the biggest value: zero is a pattern too.",
    explanation: "8 bits give 2⁸ = 256 patterns (0 to 255).",
  },
  {
    id: "sample-match-pairs",
    type: "match_pairs",
    difficulty: "challenge",
    prompt: "Match each service to the port it usually listens on.",
    pairs: [
      { id: "http", left: "Web (HTTP)", right: "`80`" },
      { id: "https", left: "Secure web (HTTPS)", right: "`443`" },
      { id: "dns", left: "DNS", right: "`53`" },
      { id: "ssh", left: "Remote login (SSH)", right: "`22`" },
    ],
    explanation: "These are the well-known default ports. Services can be configured to use others.",
  },
  {
    id: "sample-packet-path",
    type: "packet_path",
    difficulty: "core",
    prompt: "Get the packet from the **laptop** to the **web server**. ISP router B is down for maintenance, so avoid it.",
    nodes: [
      { id: "laptop", kind: "device", label: "Laptop", address: "192.168.1.20", col: 0, row: 0 },
      { id: "printer", kind: "device", label: "Printer", address: "192.168.1.30", col: 1, row: 1 },
      { id: "home", kind: "router", label: "Home router", address: "192.168.1.1", col: 1, row: 0 },
      { id: "isp-a", kind: "router", label: "ISP router A", address: "203.0.113.1", col: 2, row: 0 },
      { id: "isp-b", kind: "router", label: "ISP router B", address: "203.0.113.2", col: 2, row: 1, down: true },
      { id: "server", kind: "server", label: "Web server", address: "198.51.100.7", col: 3, row: 0 },
    ],
    links: [
      { from: "laptop", to: "home" },
      { from: "home", to: "printer" },
      { from: "home", to: "isp-a" },
      { from: "home", to: "isp-b" },
      { from: "isp-a", to: "server" },
      { from: "isp-b", to: "server" },
    ],
    source: "laptop",
    destination: "server",
    validPaths: [["laptop", "home", "isp-a", "server"]],
    explanation: "Router B is down, so the only working route is through ISP router A. The printer is a dead end.",
  },
  {
    id: "sample-terminal-command",
    type: "terminal",
    difficulty: "core",
    prompt: "Use `nslookup` to find the IP address of **example.com**.",
    intro: "Simulated Linux shell. Type help to list commands.",
    commands: [
      {
        command: "nslookup example.com",
        aliases: ["nslookup www.example.com"],
        description: "Ask DNS for example.com's address",
        output:
          "Server:\t\t127.0.0.53\nAddress:\t127.0.0.53#53\n\nNon-authoritative answer:\nName:\texample.com\nAddress: 203.0.113.10",
      },
      {
        command: "hostname",
        description: "Show this computer's name",
        output: "learner-laptop",
      },
    ],
    success: { type: "ran_command", command: "nslookup example.com" },
    explanation: "`nslookup` asks a DNS server which IP address belongs to a name.",
  },
  {
    id: "sample-terminal-answer",
    type: "terminal",
    difficulty: "core",
    prompt: "Run `ping -c 2 example.com`, then read the IP address from the output.",
    commands: [
      {
        command: "ping -c 2 example.com",
        description: "Send 2 test packets to example.com",
        output:
          "PING example.com (203.0.113.10) 56(84) bytes of data.\n64 bytes from 203.0.113.10: icmp_seq=1 ttl=56 time=11.8 ms\n64 bytes from 203.0.113.10: icmp_seq=2 ttl=56 time=12.1 ms\n\n--- example.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms",
      },
    ],
    success: { type: "answer", question: "Which IP address replied?", accepted: ["203.0.113.10"] },
    explanation: "Each reply line says who answered: `64 bytes from 203.0.113.10`.",
  },
  {
    id: "sample-teardown-laptop",
    type: "teardown",
    difficulty: "core",
    prompt: "Open the laptop: take out the **screws**, lift off the **panel**, then **unplug the battery** the way technicians do.",
    scene: "laptop",
    actions: [
      { id: "s1", part: "screw-1", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "s2", part: "screw-2", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "s3", part: "screw-3", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "s4", part: "screw-4", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "panel", part: "panel", verb: "lift", after: ["s1", "s2", "s3", "s4"], nudge: "The panel won't lift until all four screws are out." },
      { id: "battery", part: "battery-connector", verb: "unplug", after: ["panel"], nudge: "Take the panel off first." },
      {
        id: "ram",
        part: "ram",
        verb: "slide-out",
        after: ["battery"],
        nudge: "Technicians unplug the battery before touching anything else, so nothing gets a shock.",
      },
    ],
    explanation: "Screws first, then the panel, then **unplug the battery** before touching any other part. It's how repair technicians work safely.",
  },
  {
    id: "sample-teardown-phone-rebuild",
    type: "teardown",
    difficulty: "challenge",
    prompt: "Swap the phone's camera, then put the phone back together in a safe order.",
    scene: "phone",
    actions: [
      { id: "s1", part: "screw-1", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "s2", part: "screw-2", verb: "unscrew", nudge: "Unscrew it first." },
      { id: "cover", part: "back-cover", verb: "lift", after: ["s1", "s2"], nudge: "Both screws have to come out first." },
      { id: "unplug", part: "battery-connector", verb: "unplug", after: ["cover"], nudge: "Take the back cover off first." },
      { id: "camera-out", part: "camera", verb: "slide-out", after: ["unplug"], nudge: "Unplug the battery before touching other parts." },
      { id: "camera-in", part: "camera", verb: "insert", after: ["camera-out"], nudge: "Take the old camera out first." },
      { id: "replug", part: "battery-connector", verb: "plug-in", after: ["camera-in"], nudge: "Put the camera back before reconnecting the battery." },
      { id: "cover-on", part: "back-cover", verb: "insert", after: ["replug"], nudge: "Reconnect the battery before closing it up." },
      { id: "f1", part: "screw-1", verb: "fasten", after: ["cover-on"], nudge: "Put the cover back on first." },
      { id: "f2", part: "screw-2", verb: "fasten", after: ["cover-on"], nudge: "Put the cover back on first." },
    ],
    explanation: "Taking apart and putting back are mirror images: the battery is unplugged first and plugged in last, just before the cover goes back on.",
  },
  {
    id: "sample-hotspot-explore",
    type: "hotspot",
    difficulty: "core",
    prompt: "Here's what's inside a laptop. **Tap each part** to meet it.",
    scene: "laptop",
    view: "open",
    mode: "explore",
    parts: [
      { part: "cpu", job: "The brain: follows the instructions that make apps work." },
      { part: "fan", job: "Blows hot air out, so the CPU doesn't overheat." },
      { part: "ram", job: "Fast workspace for whatever you're using right now." },
      { part: "storage", job: "Keeps your files and apps, even when the power is off." },
      { part: "battery", job: "Stores the energy that runs everything." },
    ],
    explanation: "Almost every laptop has these same parts inside.",
  },
  {
    id: "sample-hotspot-tap",
    type: "hotspot",
    difficulty: "core",
    prompt: "Tap the part that keeps your photos and apps **even when the laptop is off**.",
    scene: "laptop",
    view: "open",
    mode: "tap",
    targets: ["storage"],
    explanation: "The **storage drive** (here an SSD) keeps files when the power is off. RAM forgets everything when the laptop turns off.",
  },
  {
    id: "sample-hotspot-label",
    type: "hotspot",
    difficulty: "core",
    prompt: "Label the main parts inside the laptop.",
    scene: "laptop",
    view: "open",
    mode: "label",
    labels: [
      { part: "cpu", label: "CPU" },
      { part: "ram", label: "RAM" },
      { part: "storage", label: "Storage" },
      { part: "battery", label: "Battery" },
      { part: "fan", label: "Fan" },
    ],
    explanation: "The **CPU** does the work, **RAM** holds what's in use right now, **storage** keeps files, the **battery** powers it all, and the **fan** keeps the CPU cool.",
  },
  {
    id: "sample-hotspot-files",
    type: "hotspot",
    difficulty: "challenge",
    prompt: "One of these files is pretending to be a photo. Tap it.",
    scene: "file-browser",
    mode: "tap",
    targets: ["file-fake-photo"],
    explanation: "`photo.jpg.exe` ends in **.exe**: it's a program, not a picture. The fake `.jpg` in the middle is there to trick you.",
  },
  {
    id: "sample-simulator-memory",
    type: "simulator",
    difficulty: "core",
    prompt: "Get the phone running **smoothly** with **Music**, **Maps** and **Camera** all open.",
    model: "memory",
    params: {
      ramGb: 6,
      systemGb: 1.5,
      apps: [
        { id: "music", label: "Music", gb: 0.5 },
        { id: "maps", label: "Maps", gb: 1 },
        { id: "camera", label: "Camera", gb: 1 },
        { id: "game", label: "Racing game", gb: 2.5 },
        { id: "video", label: "Video editor", gb: 2 },
      ],
    },
    controls: [
      { id: "music", kind: "toggle", label: "Music", initial: true },
      { id: "maps", kind: "toggle", label: "Maps", initial: true },
      { id: "camera", kind: "toggle", label: "Camera" },
      { id: "game", kind: "toggle", label: "Racing game", initial: true },
      { id: "video", kind: "toggle", label: "Video editor", initial: true },
    ],
    outputs: [
      { id: "smooth", kind: "device", label: "Phone", frame: "phone" },
      { id: "usedPct", kind: "bar", label: "RAM used" },
      { id: "apps", kind: "list", label: "What's in RAM" },
    ],
    goal: {
      all: [
        { target: "control", id: "music", op: "==", value: true },
        { target: "control", id: "maps", op: "==", value: true },
        { target: "control", id: "camera", op: "==", value: true },
        { target: "output", id: "smooth", op: ">=", value: 0.9 },
      ],
    },
    explanation: "Every open app takes some **RAM**. Close the big apps you aren't using (the game and the video editor) and there's room for the three you need.",
  },
  {
    id: "sample-simulator-task-manager",
    type: "simulator",
    difficulty: "core",
    prompt: "This laptop is crawling. Use the task manager to find the app hogging the CPU and end it, **without stopping your music**.",
    model: "task-manager",
    params: {
      ramGb: 8,
      processes: [
        { id: "music", label: "Music player", kind: "app", cpu: 4, ramGb: 0.4 },
        { id: "browser", label: "Web browser", kind: "app", cpu: 12, ramGb: 1.5 },
        { id: "game", label: "Frozen game", kind: "app", cpu: 88, ramGb: 2 },
        { id: "system", label: "System", kind: "system", cpu: 6, ramGb: 1.5 },
      ],
    },
    controls: [
      { id: "end-music", kind: "button", label: "End Music player", doneLabel: "Music player ended" },
      { id: "end-browser", kind: "button", label: "End Web browser", doneLabel: "Web browser ended" },
      { id: "end-game", kind: "button", label: "End Frozen game", doneLabel: "Frozen game ended" },
      { id: "end-system", kind: "button", label: "End System", doneLabel: "System ended" },
    ],
    outputs: [
      { id: "smooth", kind: "device", label: "Laptop", frame: "laptop" },
      { id: "cpu", kind: "bar", label: "CPU in use" },
      { id: "processes", kind: "list", label: "Running" },
    ],
    goal: {
      all: [
        { target: "output", id: "smooth", op: ">=", value: 0.9 },
        { target: "control", id: "end-music", op: "==", value: false },
        { target: "output", id: "crashed", op: "==", value: 0 },
      ],
    },
    explanation: "The **frozen game** was using 88% of the CPU. Ending it frees the CPU. Ending **System** would crash the laptop, and your music is fine where it is.",
  },
  {
    id: "sample-simulator-cores",
    type: "simulator",
    difficulty: "challenge",
    prompt: "Finish all the jobs in **4 seconds or less**. Try more cores and a faster clock.",
    model: "cpu-cores",
    params: {
      tasks: [
        { id: "photos", label: "Resize 100 photos", work: 16, splittable: true },
        { id: "save", label: "Save a file", work: 2, splittable: false },
      ],
    },
    controls: [
      { id: "cores", kind: "slider", label: "Cores", min: 1, max: 8, step: 1 },
      { id: "ghz", kind: "slider", label: "Clock speed", min: 1, max: 4, step: 0.5, unit: " GHz" },
    ],
    outputs: [
      { id: "seconds", kind: "timer", label: "Time to finish" },
      { id: "cores", kind: "list", label: "Work per core" },
    ],
    goal: { all: [{ target: "output", id: "seconds", op: "<=", value: 4 }] },
    explanation: "Resizing photos splits nicely across cores, so more cores help a lot. Saving one file can't be split: it runs on one core however many you have.",
  },
  {
    id: "sample-scenario",
    type: "scenario",
    difficulty: "core",
    prompt: "A message arrives from a friend's account.",
    start: "message",
    steps: [
      {
        id: "message",
        text: "**\"lol look at this!!\"** with a file attached: `photo.jpg.exe`. What do you do?",
        choices: [
          { id: "open", text: "Open it, it's from a friend", consequence: "The file is a program, not a photo. Opening it could install something harmful.", outcome: "fail" },
          { id: "check", text: "Look closely at the file name", consequence: "It ends in **.exe**, so it's a program pretending to be a photo.", next: "next-step" },
          { id: "forward", text: "Forward it to others first", consequence: "Now more people might open it. Never pass on a file you're unsure about.", outcome: "fail" },
        ],
      },
      {
        id: "next-step",
        text: "Your friend's account may have been hacked. What now?",
        choices: [
          { id: "tell", text: "Don't open it, and tell your friend and an adult", consequence: "Your friend can secure their account, and nobody gets hurt.", outcome: "success" },
          { id: "reply", text: "Reply asking them to send it again", consequence: "If the account is hacked, you're talking to the hacker, not your friend.", outcome: "fail" },
        ],
      },
    ],
    explanation: "Check the real ending of a file name before opening it. A name like `photo.jpg.exe` is a program in disguise. Tell the sender (in another way) and an adult.",
  },
  {
    id: "sample-sort-bins",
    type: "sort_bins",
    difficulty: "core",
    prompt: "Where does each thing live: **RAM** or **storage**?",
    bins: [
      { id: "ram", label: "RAM" },
      { id: "storage", label: "Storage" },
    ],
    items: [
      { id: "game-now", label: "The game you're playing right now", bin: "ram" },
      { id: "photos", label: "Your saved photos", bin: "storage" },
      { id: "unsaved", label: "An essay you haven't saved yet", bin: "ram" },
      { id: "apps", label: "Installed apps", bin: "storage" },
      { id: "page", label: "The web page you're reading", bin: "ram" },
      { id: "songs", label: "Downloaded songs", bin: "storage" },
    ],
    explanation: "**RAM** holds what you're using right now and forgets it when the power goes off. **Storage** keeps things until you delete them.",
  },
];

/** Validated samples. Throws on import if any sample breaks its schema. */
export const CARD_SAMPLES: Card[] = raw.map((c) => CardSchema.parse(c));
